name: Hello

on:
  push:
    paths-ignore:
      - '**.md'
      - '.github/workflows/**'
      - '!.github/workflows/hello.yml'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
